const imgUrl = "internal/images/";
const soundUrl = "internal/sounds/";
const lottieUrl = "internal/lottie/";

const IntroMap = {
  id: "Scene2",

  Bg: `${imgUrl}Texture-BG_Dark.svg`,

  sprites: [
    `${imgUrl}Organs/Eye.svg`,
    `${imgUrl}Organs/Nose.svg`,
    `${imgUrl}Organs/Ear.svg`,
    `${imgUrl}Organs/Tongue.svg`,
    `${imgUrl}Organs/Touch.svg`,
    `${imgUrl}Game2_Images/Eye/Rainbow_Eye.svg`,
    `${imgUrl}Game2_Images/Nose/Flower_Nose.svg`,
    `${imgUrl}Game2_Images/Ear/Speakers_Ear.svg`,
    `${imgUrl}Game2_Images/Tongue/Cup-of-Coffee_Tongue.svg`,
    `${imgUrl}Game2_Images/Skin/Pillow_Skin.svg`,
    `${imgUrl}Game2_Images/Eye/Sun_Eye.svg`,
    `${imgUrl}Game2_Images/Nose/Flower2_Nose.svg`,
    `${imgUrl}Game2_Images/Ear/Man-talking-on-phone_Ear.svg`,
    `${imgUrl}Game2_Images/Tongue/Icecream_Tongue.svg`,
    `${imgUrl}Game2_Images/Skin/Stones_Skin.svg`,
    `${imgUrl}Game2_Images/Eye/Lion_Eye.svg`,
    `${imgUrl}Game2_Images/Nose/Perfume_Nose.svg`,
    `${imgUrl}Game2_Images/Ear/Ambulance_Ear.svg`,
    `${imgUrl}Game2_Images/Tongue/Cup-of-Coffee_Tongue.svg`,
    `${imgUrl}Game2_Images/Skin/Set-of-clothes_Skin.svg`,
    `${imgUrl}Game2_Images/Eye/Moon-stars_Eye.svg`,
    `${imgUrl}Game2_Images/Nose/Pizza_Nose.svg`,
    `${imgUrl}Game2_Images/Ear/Speakers_Ear.svg`,
    `${imgUrl}Game2_Images/Tongue/Mango_Tongue.svg`,
    `${imgUrl}Game2_Images/Skin/Cotton_Skin.svg`,
    `${imgUrl}Game2_Images/Eye/Aeroplane_Eye.svg`,
    `${imgUrl}Game2_Images/Skin/Football_Skin.svg`,
    `${imgUrl}Game2_Images/Ear/Dog_Ear.svg`,
    `${imgUrl}Game2_Images/Tongue/Pop-corn_Tongue.svg`,
    `${imgUrl}Game2_Images/Skin/Feather_Skin.svg`,
    `${imgUrl}Game2_Images/Eye/Ice-cubes_Eye.svg`,
    `${imgUrl}Game2_Images/Ear/Dog_Ear.svg`,
    `${imgUrl}Game2_Images/Skin/Crayons_Skin.svg`,
    `${imgUrl}Game2_Images/Skin/Dice_Skin.svg`,
    `${imgUrl}Game2_Images/Eye/Moon-stars_Eye.svg`,
    `${imgUrl}Game2_Images/Tongue/Cup-of-Coffee_Tongue.svg`,
    `${imgUrl}Game2_Images/Eye/Sun_Eye.svg`,
    `${imgUrl}Game2_Images/Tongue/Glass-of-water_Tongue.svg`,
    `${imgUrl}Game2_Images/Eye/Papers_Eye.svg`,
    `${imgUrl}Game2_Images/Eye/Moon-stars_Eye.svg`,
    `${imgUrl}Game2_Images/Tongue/Garlic_Tongue.svg`,
    `${imgUrl}Game2_Images/Skin/Jug-of-water_Skin.svg`,
    `${imgUrl}Game2_Images/Eye/Newspaper_Eye.svg`,
    `${imgUrl}Game2_Images/Skin/Pencile_Skin.svg`,
    `${imgUrl}Game2_Images/Eye/Tiger_Eye.svg`,
    `${imgUrl}Game2_Images/Eye/Set-of-books_Eye.svg`,
    `${imgUrl}Game2_Images/Eye/Set-of-books_Eye.svg`,
    `${imgUrl}Game2_Images/Eye/Ice-mountain_Eye.svg`,
    `${imgUrl}Game2_Images/Skin/Stones_Skin.svg`,
    `${imgUrl}Game2_Images/Eye/Camp-fire_Eye.svg`,
    `${imgUrl}Game2_Images/Skin/Pencile_Skin.svg`,
    `${imgUrl}Game2_Images/Nose/Incense-stick_Nose.svg`,
    `${imgUrl}Game2_Images/Skin/Shirt_Skin.svg`,
    `${imgUrl}Game2_Images/Skin/Teddy_Skin.svg`,
    `${imgUrl}Game2_Images/Eye/Sun_Eye.svg`,
    `${imgUrl}Audio_replay_button.svg`,
  ],

  sounds: [
    `${soundUrl}Game2_sound.mp3`,
    `${soundUrl}game2-sounds/sense-of-eye.mp3`,
    `${soundUrl}game2-sounds/sense-of-smell.mp3`,
    `${soundUrl}game2-sounds/sense-of-hearing.mp3`,
    `${soundUrl}game2-sounds/sense-of-taste.mp3`,
    `${soundUrl}game2-sounds/sense-of-touch.mp3`,
    `${soundUrl}correct-answer-Game2.mp3`,
    `${soundUrl}wrong-answer-Game2.mp3`,
    `${soundUrl}mouse-click.mp3`,
  ],

  lottie: [],

  select: ["Eye", "Nose", "Ear", "Tongue", "Skin"],
};

export default IntroMap;
